title: Annalytic
email: azaleamollis@outlook.com
description: Anna Monus | Full-stack technical writer
author: Anna Monus
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.annalytic.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: azaleamollis
github_username:  azaleamollis

# Social Profiles
twitter_username: azaleamollis
github_username: azaleamollis

# Build settings
markdown: kramdown
highlighter: rouge

#theme: jekyll-theme-clean-blog
remote_theme: jekyll-theme-clean-blog
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
